Corp_Management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url("favicon.ico"))),
    path('', include('main.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),


    path('performance/yearly', views.annual_performance, name='yearly_performance'),
    path('performance/monthly', views.monthly_performance, name='monthly_performance'),


    path('client/register', views.register_client, name='register_client'),
    path('clients', views.ClientList.as_view(), name='client_list'),
    path('client/<str:pk>', views.ClientDetail.as_view(), name='client_detail'),


    path('suppliers', views.SupplierList.as_view(), name='supplier_list'),
    path('supplier/create', views.CreateSupplier.as_view(), name='supplier_create'),
    path('supplier/<str:pk>', views.SupplierDetail.as_view(), name='supplier_detail'),
    path('supplier/<str:pk>/download', views.price_download, name='supplier_download'),


    path('order/create', views.create_order, name='create_order'),
    path('order/list', views.OrderList.as_view(), name='order_list'),
    path('order/download/<str:pk>', views.order_download, name='order_download'),
    path('order/<str:pk>', views.OrderDetail.as_view(), name='order_detail'),
    path('order/<str:pk>/purchase/create', views.add_purchase, name='purchase_add'),
    path('order/<str:pk>/purchase/edit', views.edit_purchase, name='purchase_edit'),
    path('order/<str:pk>/purchase/detail', views.purchase_detail, name='purchase_detail'),
    path('order/<str:pk>/production/create', views.production_create, name='production_add'),
    path('order/<str:pk>/production/list', views.ProductionList.as_view(), name='production_list'),


    path('staff/position/create', views.create_position, name='create_position'),
    path('staff/register', views.staff_register, name='register'),
    path('staff/list', views.StaffList.as_view(), name='staff_list'),
    path('staff/<str:pk>', views.StaffDetail.as_view(), name='staff_detail'),
    path('staff/edit/<str:pk>', views.staff_edit, name='staff_edit'),


    path('item/add', views.AddItem.as_view(), name='item_add'),
    path('item/list', views.ItemList.as_view(), name='item_list'),
    path('item/<str:pk>', views.ItemDetail.as_view(), name='item_detail'),


    path('storage/create', views.storage_change, name='create_change'),
    path('storage/update/<str:pk>', views.update_storage_change, name='storage_change'),
    path('storage/complete/<str:pk>', views.change_complete, name='change_complete'),
    path('storage/change/item/delete/<str:pk>', views.delete_item_change, name='delete_item_change'),
    path('storage/<str:pk>', views.change_detail, name='change_detail'),


    path('production/<str:pk>', views.production_detail, name='production_detail'),

    path('order/<str:pk>/quality/list', views.QualityList.as_view(), name='quality_list'),
    path('order/<str:pk>/quality/create', views.quality_create, name='quality_create'),
    path('quality/<str:pk>', views.quality_detail, name='quality_detail'),
]

main/models.py
from django.contrib.auth.models import User
from django.core.validators import *
from django.db import models
from django.urls import reverse
from datetime import datetime
from django.utils.text import slugify

SCALES = [
    ("0~10", "0~10"),
    ("11~50", "11~50"),
    ("51~100", "51~100"),
    ("101~500", "101~500"),
    (">500", ">500"),
]


class Company(models.Model):
    name = models.CharField(max_length=20)
    name_slug = models.SlugField()

    def save(self, *args, **kwargs):
        self.name_slug = slugify(self.name)
        super(Company, self).save(*args, **kwargs)


class Perm(models.Model):
    position_all = models.BooleanField(default=False)
    order_detail = models.BooleanField(default=False)
    order_list = models.BooleanField(default=False)
    order_create = models.BooleanField(default=False)
    order_edit = models.BooleanField(default=False)
    order_delete = models.BooleanField(default=False)
    client_list = models.BooleanField(default=False)
    client_detail = models.BooleanField(default=False)
    client_edit = models.BooleanField(default=False)
    client_delete = models.BooleanField(default=False)
    client_create = models.BooleanField(default=False)
    supplier_list = models.BooleanField(default=False)
    supplier_detail = models.BooleanField(default=False)
    supplier_create = models.BooleanField(default=False)
    supplier_delete = models.BooleanField(default=False)
    supplier_edit = models.BooleanField(default=False)
    company = models.BooleanField(default=False)
    staff_list = models.BooleanField(default=False)
    staff_detail = models.BooleanField(default=False)
    staff_create = models.BooleanField(default=False)
    staff_delete = models.BooleanField(default=False)
    staff_edit = models.BooleanField(default=False)
    staff_performance = models.BooleanField(default=False)
    item_list = models.BooleanField(default=False)
    item_create = models.BooleanField(default=False)
    item_detail = models.BooleanField(default=False)
    item_delete = models.BooleanField(default=False)
    stock_change_create = models.BooleanField(default=False)
    stock_change_list = models.BooleanField(default=False)
    self_order = models.BooleanField(default=True)


class Position(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=20, default="暂定")
    perms = models.OneToOneField(Perm, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name


class Staff(models.Model):
    account = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=20, validators=[RegexValidator('^[0-9 +]*$', message="手机号错误")])
    email = models.EmailField(null=True, blank=True)
    staff_id = models.CharField(max_length=50, error_messages={'required': '请输入工号'})
    national_id = models.CharField(max_length=18, validators=[
        MinLengthValidator(18, message="身份证格式错误"),
        RegexValidator('^[0-9a-zX]*$', message="身份证格式错误")
    ])
    position = models.ForeignKey(Position, on_delete=models.SET_NULL, null=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True, blank=True)
    status = models.CharField(max_length=10, choices=[("on_post", "在职"), ("left", "离职")], default="on_post")
    employed_date = models.DateField()
    leaving_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.name


class MonthlyPerformance(models.Model):
    owner = models.ForeignKey(Staff, on_delete=models.CASCADE, related_name='monthly')
    performance = models.FloatField(default=0)
    year = models.IntegerField(default=datetime.now().year, blank=True)
    month = models.IntegerField(default=datetime.now().month, blank=True)


class AnnualPerformance(models.Model):
    owner = models.ForeignKey(Staff, on_delete=models.CASCADE, related_name='yearly')
    performance = models.FloatField(default=0)
    year = models.IntegerField(default=datetime.now().year, blank=True)


class Client(models.Model):
    company = models.ForeignKey(Company, on_delete=models.PROTECT, related_name='client', null=True, blank=True)
    client_id = models.CharField(max_length=20, blank=True)
    name = models.CharField(max_length=200)
    source = models.CharField(max_length=20, choices=[
        ('assigned', '公司分配'),
        ('custom', '海关数据'),
        ('exhibition', '展会资源'),
        ('other', '其他方式')
    ])
    level = models.CharField(max_length=20, choices=[
        ('intended', '意向客户'),
        ('potential', '潜在客户'),
        ('not_intended', '无意向客户'),
        ('ordered', '下单客户')
    ])
    client_type = models.CharField(max_length=20, choices=[
        ('individual', '个人客户'),
        ('enterprise', '品牌公司'),
        ('foreign', '外贸公司'),
        ('internation', '跨境商超'),
        ('other', '其他')
    ])
    scale = models.CharField(max_length=20, choices=SCALES)
    market = models.CharField(max_length=10, null=True)
    country = models.CharField(max_length=20)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField(max_length=50, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    order_in_progress = models.IntegerField(null=True, default=0)
    order_completed = models.IntegerField(null=True, default=0)
    registrant = models.CharField(max_length=10)
    related_staff = models.ForeignKey(Staff, on_delete=models.RESTRICT)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('client_detail', args=(str(self.id)))


class ClientContact(models.Model):
    corp = models.ForeignKey(Client, on_delete=models.CASCADE, blank=True)
    name = models.CharField(max_length=10)
    gender = models.CharField(max_length=10, choices=[('male', '男'), ('female', '女'), ('other', '其他')])
    position = models.CharField(max_length=50)
    dob = models.DateField()
    phonenum = models.CharField(max_length=20)
    email = models.EmailField()
    remark = models.TextField()


class ClientCommunication(models.Model):
    METHODS = [
        ('email', '邮件来往'),
        ('call', '电话交流'),
        ('f2f', '客户面访'),
        ('qq', 'QQ交流'),
        ('wechat', '微信交流'),
        ('other', '其他方式')
    ]
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    client_name = models.CharField(max_length=30)
    creator = models.ForeignKey(Staff, on_delete=models.PROTECT)
    method = models.CharField(max_length=10, choices=METHODS)
    content = models.FileField()
    date = models.DateField()
    next_date = models.DateField()
    next_method = models.CharField(max_length=10, choices=METHODS)
    next_plan = models.TextField()


class Supplier(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    commodity = models.CharField(max_length=20, null=True, choices=[
        ('brush_hair', '刷毛'),
        ('pipe', '口管'),
        ('handle', '刷柄'),
        ('production', '人工')
    ])
    scale = models.CharField(max_length=10, choices=SCALES)
    established_date = models.DateField(null=True, blank=True)
    price = models.FileField(null=True)
    invoice = models.TextField(max_length=200)
    remark = models.TextField(max_length=200)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('supplier_detail', kwargs={'pk': self.pk})


class SupplierContact(models.Model):
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    name = models.CharField(max_length=10)
    position = models.CharField(max_length=20)
    phonenum = models.CharField(max_length=20)
    email = models.EmailField()
    remark = models.TextField(null=True, blank=True, max_length=200)


class Item(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, blank=True, null=True)
    item_id = models.CharField(max_length=20)
    name = models.CharField(max_length=20)
    type = models.CharField(max_length=10, null=True, blank=True, choices=[
        ('product', '产品'),
        ('material', '原料'),
    ])
    amount = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    # unit = models.CharField(max_length=5)
    spec = models.CharField(max_length=200)
    product_type = models.CharField(max_length=6, null=True, blank=True, choices=[
        ('single', '单品'),
        ('bound', '套装')
    ])
    hair = models.CharField(max_length=30, null=True, blank=True)
    pipe = models.CharField(max_length=30, null=True, blank=True)
    handle = models.CharField(max_length=30, null=True, blank=True)
    min_order = models.IntegerField(null=True, blank=True)
    package = models.BooleanField(default=False)
    package_price = models.FloatField(default=0.0, blank=True)
    pattern = models.BooleanField(default=False)
    reference = models.URLField(null=True, blank=True)
    remark = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name


class Order(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True, blank=True)
    client = models.ForeignKey(
        Client,
        on_delete=models.PROTECT,
        null=True
    )
    creator = models.ForeignKey(Staff, related_name='created_order', on_delete=models.PROTECT, null=True)
    staff = models.ManyToManyField(Staff, related_name='orders')
    # staff1 = models.CharField(max_length=20)
    # staff2 = models.CharField(max_length=20)
    order_num = models.CharField(max_length=20, blank=True, null=True, validators=[
        RegexValidator('^[0-9]*$', message='订单号格式错误', ),
    ])
    order_type = models.CharField(max_length=10, choices=[('normal', '大货订单'), ('sample', '样品订单')])
    production_type = models.CharField(max_length=10, choices=[('stoke', '库存'), ('produce', '生产')])

main/templates/order/create.html
{% extends 'main/form.html' %}
{% load static %}

{% block form %}

    {{ form.as_p }}
    <div class="mb-3">

  <label for="formFileMultiple" class="form-label">上传附件</label>
  <input class="dropzone" type="file" name="files" multiple>
</div>


    <input type="submit" value="提交订单" class="btn btn-outline-secondary">
{% endblock %}

main/templates/order/detail.html
{% extends 'main/base.html' %}
{% block content %}

    <style>
    td, th{
        border: 1px solid slateblue;
        padding: 0 20px;
    }
    </style>



    <div class="position-absolute top-0 start-50 translate-middle-x" style="margin-top: 50px;background: rgba(204, 255, 255, 0.8); padding: 30px; border-radius: 30px; width: 800px">
    <div style="text-align: center;"><h1>{{ order.order_num }}</h1></div>
        客户: <a href="{% url 'client_detail' order.client.pk %}" style="margin-left: 27px"> {{ order.client }}</a><br />
        创建者: <a href="{% url 'staff_detail' order.creator.pk %}" style="margin-left: 10px">{{ order.creator }}</a><br/><br/>
        相关员工:
            <table>
        {% for i in staff %}
            <tr><td><a href="{% url 'staff_detail' i.pk %}"> {{ i.name }}</a></td> <td>{{ i.position.name }}</td></tr>
        {% endfor %}
        </table><br/>

        订单类型: {{ order.get_order_type_display }}<br/>

        创建时间: {{ order.created }}<br/>

        商品: <a href="{% url 'item_detail' order.item.pk %}" style="margin-left: 10px"> {{ order.item }} </a><br/>

        规格: {{ order.specs }}<br/>

        商品单价: {{ order.ppu }}<br/>

        订购数量: {{ order.amount }}<br />

        商品总价: {{ order.price }}<br />

        送货地址: {{ order.address }}<br/>

        订金: {{ order.deposit }}<br/>

        尾款: {{ order.remaining }}<br />
    {% if order.description %}
        备注: {{ order.description }}
    {% endif %}


{% if not order.completed %}
    <br/>
    <form method="post" action="">
        {% csrf_token %}
        {{ form }} <button type="submit" class="btn btn-outline-light btn-sm">更新</button><br/>
    </form>
        {% endif %}
    <div>
    {% if current %}
        <br />
        当前状态: <strong style="color: red; margin-left: 10px">
        {% if type == 'normal' %}
        {{ current.get_status_display }}
            {% else %}
            {{ current.get_sample_status_display }}
            {% endif %}
        </strong>
        <br/>
    {% endif %}
    <br />
    </div>
    {% if status_history %}
        <div>
            历史状态:
        <div>
        <div style="margin-left: 150px">
        <table style="text-align: center">
        <tr><th>更新后状态</th><th>更新时间</th><th>执行人</th></tr>
        {% if type == 'normal' %}
            {% for status in status_history %}
                <tr><td>{{ status.get_status_display }}</td> <td>{{ status.time }}</td> <td>{{ status.creator }}</td></tr>
            {% endfor %}

        {% else %}

            {% for status in status_history %}
                <tr><td>{{ status.get_sample_status_display }}</td> <td>{{ status.time }}</td> <td>{{ status.creator }}</td></tr>
            {% endfor %}<br/>
        {% endif %}
        </table>
        </div>
    {% endif %}

    <br/>
    <hr />
    <br/>

<table style="text-align: center; margin-left: 200px">
    <tr>
        <th>{% if order.purchase %}<a href="{% url 'purchase_detail' order.pk %}">{% else %}<a href="{% url 'purchase_add' order.pk %}">{% endif %}采购管理</a></th>
        <th><a href="{% url 'production_list' order.pk%}">生产任务</a></th>
        <th><a href="{% url 'quality_list' order.pk%}">质检任务</a></th>
    </tr>

</table>
{% if attachments %}
    <br/>
    附件: <br/>
    {% for attachment in attachments %}
        <a href="{% url 'order_download' attachment.pk %}" class="icon-link icon-link-hover" style="--bs-icon-link-transform: translate3d(0, -.125rem, 0);">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box2-fill" viewBox="0 0 16 16">
  <path d="M3.75 0a1 1 0 0 0-.8.4L.1 4.2a.5.5 0 0 0-.1.3V15a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1V4.5a.5.5 0 0 0-.1-.3L13.05.4a1 1 0 0 0-.8-.4h-8.5ZM15 4.667V5H1v-.333L1.5 4h6V1h1v3h6l.5.667Z"></path>
</svg>
            {{ attachment }}
        </a><br/>
    {% endfor %}
{% endif %}



    </div>



{% endblock %}

main/templates/order/list.html
{% extends 'main/list.html' %}

{% block placeholder %}订单号/客户名/商品名/员工名{% endblock %}


{% block table %}


<table style="background: gainsboro">
    <tr><th>订单号</th><th>客户</th><th>订单状态</th></tr>
</table>
    {% for order in object_list %}

            <a href="{% url 'order_detail' order.pk %}"
               class="list-group-item list-group-item-action list-group-item-dark
               d-flex justify-content-between align-items-center" style="padding: 0">
                <ul class="list-group list-group-horizontal" style="margin: 0">
                    <li class="list-group-item">{{ order.order_num }}</li>
                    <li class="list-group-item">{{ order.client }}</li>
                <li class="list-group-item">
                {% for status in order.status.all %}
                    {% if order.order_type == 'normal' and status.current == True %}
                    {{ status.get_status_display }}
                    {% elif order.order_type == 'sample' and status.current == True %}
                        {{ status.get_sample_status_display }}
                    {% endif %}
                    {% endfor %}
                </li>
                </ul>
            </a>

    {% endfor %}



{% endblock %}

main/templates/order/production_create.html
{% extends 'main/form.html' %}

{% block form %}

    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">创建</button>

{% endblock %}

main/templates/order/production_detail.html
{% extends 'main/base.html' %}
{% block content %}

    <div class="position-absolute top-0 start-50 translate-middle-x" style="margin-top: 50px;background: rgba(255, 255, 255, 0.8); padding: 30px; border-radius: 30px;">

    <p>订单: {{ production.order }}</p>
        <p>生产编号: {{ production.production_id }}</p>
        <p>产品: <a href="{% url 'item_detail' production.item.pk %}"> {{ production.item }}</a></p>
    <p>生产数量: {{ production.amount }} {{ production.unit }}</p>
        <p>状态: {{ production.status}}</p>
    <p>创建日期: {{ production.date_created }}</p>
    <p>完成日期: {{ production.date_completed }}</p>
    <p>跟单员: {{ production.staff1 }}</p>
    <p>业务员: {{ production.staff2 }}</p>
    {% if production.file %}
    <p>附件: {{ production.file }}</p>
    {% endif %}
        {% if production.remark %}
    <p>备注: {{ production.remark }}</p>
    {% endif %}

    </div>


{% endblock %}

main/templates/order/production_list.html
{% extends 'main/list.html' %}

{% block placeholder %}{% endblock %}

{% block add %}
    <a href="{% url 'production_add' pk %}"><button class="btn btn-outline-primary">添加</button></a>
{% endblock %}


{% block table %}


<table style="background: gainsboro">
    <tr><th>编号</th><th>物品</th><th>状态</th></tr>
</table>
    {% for production in object_list %}

            <a href="{% url 'production_detail' production.pk %}"
               class="list-group-item list-group-item-action list-group-item-dark
               d-flex justify-content-between align-items-center" style="padding: 0">
                <ul class="list-group list-group-horizontal" style="margin: 0">
                    <li class="list-group-item">{{ production.production_id }}</li>
                    <li class="list-group-item">{{ production.item.name }}</li>
                    <li class="list-group-item">{{ production.get_status_display }}</li>
                </ul>
            </a>

    {% endfor %}



{% endblock %}